
language: php

sudo: false

addons:
  apt:
    packages:
      - tidy

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly
  - 7.0

before_install:
  - pip install --user codecov

env:
  global:
    - DB=MYSQL CORE_RELEASE=3.2
    - MODULE_PATH=locator
    - COVERAGE=1

matrix:
  allow_failures:
    - php: hhvm-nightly
    - php: 7.0
  include:
    - php: 5.6
      env: DB=PGSQL
    - php: 5.6
      env: DB=SQLITE
    - php: hhvm
      env: DB=MYSQL
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.2 COVERAGE=1
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.2
    - php: 5.6
      env: DB=SQLITE CORE_RELEASE=3.2
    - php: 5.5
      env: DB=MYSQL CORE_RELEASE=3.2
    - php: 5.4
      env: DB=MYSQL CORE_RELEASE=3.2
    - php: 5.3
      env: DB=MYSQL CORE_RELEASE=3.2
    - php: hhvm
      env: DB=MYSQL CORE_RELEASE=3.2


before_script:
  - phpenv rehash
  - composer self-update || true
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  # Execute tests with no coverage.  This is the fastest option
  - "if [ \"$COVERAGE\" = \"0\" ]; then vendor/bin/phpunit $MODULE_PATH/tests/; fi"

  # Execute tests with coverage.  Do this for a small
  - "if [ \"$COVERAGE\" = \"1\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/; fi"

after_script:
  - "if [ \"$COVERAGE\" = \"1\" ]; then mv coverage.clover ~/build/$TRAVIS_REPO_SLUG/; fi"
  - cd ~/build/$TRAVIS_REPO_SLUG
  - wget https://scrutinizer-ci.com/ocular.phar
  - "if [ \"$COVERAGE\" = \"1\" ]; then travis_retry codecov && travis_retry php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi"

